mysql:
  container_name: mysql
  restart: always
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: 'root' # TODO: Change this
    MYSQL_USER: 'root'
    MYSQL_PASS: 'root'
  volumes:
    - ./data:/var/lib/mysql
  ports: 
    - "3306:3306"
